# Generated by Django 3.0.2 on 2020-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishuser',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='возраст'),
        ),
    ]
